In [1]:
from __future__ import print_function
import torch

In [2]:
print(torch.__version__)

1.5.0+cu101


In [3]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4148])
0.41475337743759155


In [4]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y

    print(z)
    print(z.to("cpu", torch.double))

tensor([1.4148], device='cuda:0')
tensor([1.4148], dtype=torch.float64)
