### Reference: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

In [1]:
from __future__ import print_function
import torch

In [2]:
torch.__version__

'1.5.1'

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[ 5.6753e-10,  4.5766e-41,  5.6893e-10],
        [ 4.5766e-41,  1.2966e+02, -2.0005e+00],
        [ 1.2967e+02, -1.0845e-19,  5.6752e-10],
        [ 4.5766e-41, -3.0044e+04,  4.3081e-40],
        [ 5.6449e-10,  4.5766e-41,  1.2134e-32]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8729, 0.2262, 0.6003],
        [0.4408, 0.6554, 0.0503],
        [0.8224, 0.0244, 0.7989],
        [0.2861, 0.9801, 0.7057],
        [0.1093, 0.5164, 0.2383]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.zeros(5, 3, dtype=torch.float32)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5260,  0.9864,  0.1597],
        [-0.4278,  0.7239,  1.4143],
        [ 1.2154,  1.5770, -0.5353],
        [ 0.5417, -0.4839, -0.9587],
        [-0.4635,  0.0996,  1.1838]])


In [12]:
print(x.new_ones(3, 2, dtype=torch.long))

tensor([[1, 1],
        [1, 1],
        [1, 1]])


In [13]:
print(x.size())

torch.Size([5, 3])


In [14]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.2170,  1.3771,  0.9961],
        [-0.2152,  0.9710,  2.1292],
        [ 1.4641,  1.9620, -0.1214],
        [ 0.7969,  0.1295, -0.8334],
        [-0.1589,  0.4201,  2.0621]])


In [15]:
print(torch.add(x, y))

tensor([[-0.2170,  1.3771,  0.9961],
        [-0.2152,  0.9710,  2.1292],
        [ 1.4641,  1.9620, -0.1214],
        [ 0.7969,  0.1295, -0.8334],
        [-0.1589,  0.4201,  2.0621]])


In [16]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.2170,  1.3771,  0.9961],
        [-0.2152,  0.9710,  2.1292],
        [ 1.4641,  1.9620, -0.1214],
        [ 0.7969,  0.1295, -0.8334],
        [-0.1589,  0.4201,  2.0621]])


In [17]:
y.add_(x)
print(y)

tensor([[-0.2170,  1.3771,  0.9961],
        [-0.2152,  0.9710,  2.1292],
        [ 1.4641,  1.9620, -0.1214],
        [ 0.7969,  0.1295, -0.8334],
        [-0.1589,  0.4201,  2.0621]])


In [18]:
x.copy_(y)
print(x)

tensor([[-0.2170,  1.3771,  0.9961],
        [-0.2152,  0.9710,  2.1292],
        [ 1.4641,  1.9620, -0.1214],
        [ 0.7969,  0.1295, -0.8334],
        [-0.1589,  0.4201,  2.0621]])


In [19]:
print(x[:, 1])

tensor([1.3771, 0.9710, 1.9620, 0.1295, 0.4201])


In [20]:
print(x[1, :])

tensor([-0.2152,  0.9710,  2.1292])


In [21]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
print(x)
print(y)
print(z)

tensor([[ 0.6515, -0.8133, -1.9097, -0.8160],
        [ 0.3340, -1.6598, -0.4324,  0.6181],
        [-0.3387, -2.8855,  0.3400,  1.6888],
        [ 1.8858,  0.2492,  1.1510,  0.6515]])
tensor([ 0.6515, -0.8133, -1.9097, -0.8160,  0.3340, -1.6598, -0.4324,  0.6181,
        -0.3387, -2.8855,  0.3400,  1.6888,  1.8858,  0.2492,  1.1510,  0.6515])
tensor([[ 0.6515, -0.8133, -1.9097, -0.8160,  0.3340, -1.6598, -0.4324,  0.6181],
        [-0.3387, -2.8855,  0.3400,  1.6888,  1.8858,  0.2492,  1.1510,  0.6515]])


In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2117])
0.21166083216667175


In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [27]:
print(type(b))

<class 'numpy.ndarray'>


In [28]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [29]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
